Feature: ADD SOCKETS

  Scenario:
    Given I HAVE A ROOM OBJECT BUILDER
    When I ADD A SOCKET
    Then THE SIZE OF THE SOCKET SHOULD BE CALCULATED
    And THE SOCKET SIZE IS SUBTRACTED FROM THE SIZE OF THE WALL
